name: qmlcreator
version: 1.5.0
summary: A lightweight QML IDE
description: |
  QML Creator is a simple and lightweight IDE for projects based on QML & JavaScript.

  Features:
    - Responsive interface
    - Simple project layout style
    - Syntax highlighting
    - Debug console overlay
    - Runs on desktops as well as mobile devices

confinement: strict
icon: resources/images/icon512.png
base: core24

platforms:
  amd64:
  arm64:
  armhf:

apps:
  qmlcreator:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/lomiri-launch
    command: usr/bin/qmlcreator
    plugs:
      - x11
      - wayland
      - mir
      - desktop
      - opengl
      - alsa
      - pulseaudio
      - home
      - removable-media
      - network
      - network-bind
      - maliit
      - media-hub
      - location-observe
      - screen-inhibit-control

plugs:
  lomiri-ui-toolkit:
    interface: content
    target: $SNAP/lomiri-ui-toolkit
    default-provider: lomiri-ui-toolkit-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/share/X11/xkb:
    symlink: $SNAP/lomiri-ui-toolkit/usr/share/X11/xkb
  /usr/share/icons:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds

parts:
  qmlcreator:
    source: .
    build-snaps:
      - lomiri-ui-toolkit-core24
    plugin: qmake
    qmake-project-file: qmlcreator.pro
    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/bin
      cp -a /snap/lomiri-ui-toolkit-core24/current/command-chain/lomiri-launch ${CRAFT_PRIME}/bin/lomiri-launch
    build-packages:
      - qt5-qmake
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - qtmultimedia5-dev
      - libqt5webkit5-dev
      - qtbase5-dev
      - libevdev-dev
      - libudev-dev
      - qt3d5-dev
      - libqt5websockets5-dev
      - libqt5sensors5-dev
  gpu-2404:
    after:
      - qmlcreator
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
